name: Run lint and tests

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
      - name: 'Run black'
        uses: psf/black@23.1.0
        with:
          version: "23.1.0"
      - name: Pre Commit Hooks
        uses: pre-commit/action@v3.0.0
        env:
          SKIP: no-commit-to-branch
        with:
          extra_args: --all-files --show-diff-on-failure


  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: 3.10.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: coverage run --source=. -m pytest
